# GoReleaser configuration for CMDB KubeExplorer
# Documentation: https://goreleaser.com

version: 2
project_name: cmdb-kubeexplorer

before:
  hooks:
    # Build frontend before Go compilation (gets embedded)
    - sh -c "cd web && npm install && npm run build"
    # Clean stale files from previous builds before copying fresh output
    - sh -c "rm -rf internal/static/dist && mkdir -p internal/static/dist"
    - sh -c "cp -r web/dist/* internal/static/dist/"

builds:
  - id: cmdb-kubeexplorer
    main: ./cmd/explorer
    binary: kubectl-cmdb-kubeexplorer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: cmdb
    name: cmdb-kubeexplorer
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## CMDB KubeExplorer v{{.Version}}

    **Modern Kubernetes visibility.** Local-first. No account. No cloud dependency. Fast.

    Topology, event timeline, and service traffic — plus resource browsing and Helm management. Open source. Free forever.

    ### Installation

    **Homebrew (macOS/Linux):**
    ```bash
    brew install cmdb/tap/cmdb-kubeexplorer
    ```

    **Scoop (Windows):**
    ```powershell
    scoop bucket add cmdb https://github.com/cmdb/scoop-bucket
    scoop install cmdb-kubeexplorer
    ```

    **PowerShell (Windows):**
    ```powershell
    irm https://raw.githubusercontent.com/cmdb/cmdb-kubeexplorer/main/install.ps1 | iex
    ```

    **Manual (macOS Apple Silicon):**
    ```bash
    curl -LO https://github.com/cmdb/kubeexplorer/releases/download/v{{.Version}}/cmdb-kubeexplorer_v{{.Version}}_darwin_arm64.tar.gz
    tar -xzf cmdb-kubeexplorer_v{{.Version}}_darwin_arm64.tar.gz
    sudo mv kubectl-cmdb-kubeexplorer /usr/local/bin/
    ```

    **Manual (macOS Intel):**
    ```bash
    curl -LO https://github.com/cmdb/kubeexplorer/releases/download/v{{.Version}}/cmdb-kubeexplorer_v{{.Version}}_darwin_amd64.tar.gz
    tar -xzf cmdb-kubeexplorer_v{{.Version}}_darwin_amd64.tar.gz
    sudo mv kubectl-cmdb-kubeexplorer /usr/local/bin/
    ```

    **Manual (Linux amd64):**
    ```bash
    curl -LO https://github.com/cmdb/kubeexplorer/releases/download/v{{.Version}}/cmdb-kubeexplorer_v{{.Version}}_linux_amd64.tar.gz
    tar -xzf cmdb-kubeexplorer_v{{.Version}}_linux_amd64.tar.gz
    sudo mv kubectl-cmdb-kubeexplorer /usr/local/bin/
    ```

    ### Desktop App

    **Homebrew (macOS):**
    ```bash
    brew install --cask cmdb/tap/cmdb-kubeexplorer-desktop
    ```

    **Debian/Ubuntu:**
    ```bash
    curl -LO https://github.com/cmdb/kubeexplorer/releases/download/v{{.Version}}/cmdb-kubeexplorer-desktop_v{{.Version}}_linux_amd64.deb
    sudo dpkg -i cmdb-kubeexplorer-desktop_v{{.Version}}_linux_amd64.deb
    ```

    **Fedora/RHEL:**
    ```bash
    curl -LO https://github.com/cmdb/kubeexplorer/releases/download/v{{.Version}}/cmdb-kubeexplorer-desktop_v{{.Version}}_linux_amd64.rpm
    sudo rpm -i cmdb-kubeexplorer-desktop_v{{.Version}}_linux_amd64.rpm
    ```

    **Scoop (Windows):**
    ```powershell
    scoop bucket add cmdb https://github.com/cmdb/scoop-bucket
    scoop install cmdb-kubeexplorer-desktop
    ```

    **Windows (direct download):** Download from the assets below.

    ### CLI

    Then run: `kubectl cmdb-kubeexplorer`

# Homebrew formula (publishes to cmdb/homebrew-tap)
brews:
  - name: cmdb-kubeexplorer
    repository:
      owner: cmdb
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/cmdb/kubeexplorer"
    description: "Modern Kubernetes visibility — topology, traffic, and Helm management"
    license: "Apache-2.0"
    install: |
      bin.install "kubectl-cmdb-kubeexplorer"
      bin.install_symlink "kubectl-cmdb-kubeexplorer" => "cmdb-kubeexplorer"
    test: |
      system "#{bin}/kubectl-cmdb-kubeexplorer", "--version"

# Scoop manifest (publishes to cmdb/scoop-bucket)
scoops:
  - name: cmdb-kubeexplorer
    repository:
      owner: cmdb
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    homepage: "https://github.com/cmdb/kubeexplorer"
    description: "Modern Kubernetes visibility — topology, traffic, and Helm management"
    license: Apache-2.0
    post_install: ["Write-Host 'Run: kubectl-cmdb-kubeexplorer or cmdb-kubeexplorer' -ForegroundColor Green"]
